<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> The Promise API</title>
    <!-- CSS Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>

    </style>
</head>

<body>
    <h1>The Promise API</h1>

    <script>
        let p1 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve("value 1");
            }, 1000);
        });

        let p2 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve("value 2");
            }, 2000);
        });

        let p3 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve("value 3");
            }, 3000);
        });

        let p4 = new Promise((resolve, reject) => {
            setTimeout(() => {
                reject(new Error("Something gone Wrong....!"));
            }, 500);
        });
        
        // Normal Execution
        // p1.then((value)=>{
        //     console.log(value);
        // });
        // p2.then((value)=>{
        //     console.log(value);
        // });
        // p3.then((value)=>{
        //     console.log(value);
        // });

        // Promise.all
        let a = Promise.all([p1, p2, p3]);
        a.then((value) => {
            console.log(value, "\nPromise all array");
        }).catch((error) => {
            console.log(error);
        })

        // Promise.all (with rejected value)
        let b = Promise.all([p1, p2, p3, p4]); // Only gives rejected promise output
        b.then((value) => {
            console.log(value, "\nPromise all array with one promise which is rejected");
        }).catch((error) => {
            console.log(error);
        })

        // Promise.allSettled (with rejected value)
        let c = Promise.allSettled([p1, p2, p3, p4]); // Only gives rejected promise output
        c.then((value) => {
            console.log(value, "\nPromise all array with one promise which is rejected without catch using allSetteled");
        })

        // Promise.race (with no reject values)
        let d = Promise.race([p1, p2, p3]);
        d.then((value) => {
            console.log(value, "\nwinner of Promises");
        });

        // Promise.race (reject values)
        let e = Promise.race([p1, p2, p3, p4]);
        e.then((value) => {
            console.log(value);
        }).catch((error) => {
            console.log(error, "\nthrown an error first");
        });

        // Promise.any 
        let f = Promise.any([p1, p2, p3, p4]);
        f.then((value) => {
            console.log(value, "any promise which resolve first excluding error")
        });
        
        // Promise.resolve 
        let res = Promise.resolve(65);
        res.then((value) => {
            console.log(value);
        })

        // Promise.reject
        let rej = Promise.reject(new Error("Tu pagal hai kya!!!!!"));
        rej.then((value) => {
            console.log(value);
        }).catch((error) => {
            console.log(error);
        })
    </script>

    <!-- JS Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>